language: ruby

install:
 - jdk_switcher use oraclejdk7
 # Warning: Setting DYLD_* vars can break dynamic linking.
 - unset DYLD_LIBRARY_PATH

 # Install gcc-4.9 system wide [default is gcc-4.6]
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y > /dev/null
 - sudo apt-get update -qq > /dev/null
 - sudo apt-get install -y libyajl-dev libxml2-dev libxqilla-dev > /dev/null
 - sudo apt-get install -y libstdc++-4.9-dev > /dev/null
 - sudo apt-get install -y g++-4.9 gfortran-4.9 > /dev/null
 - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90 > /dev/null
 - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 90 > /dev/null
 - sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-4.9 90 > /dev/null

 # Install linuxbrew essentials
 - sudo apt-get install -qq build-essential curl git m4 ruby texinfo libbz2-dev libcurl4-openssl-dev libexpat-dev libncurses-dev zlib1g-dev

 # Install BLAS, LAPACK
 - sudo apt-get install -qq libblas-dev liblapack-dev
 # Install openmpi if necessary
 #- if [[ -z `which mpicc` ]]; then sudo apt-get install -qq openmpi-bin; fi
 #- sudo apt-get remove -y openmpi-bin libopenmpi-dev
 - sudo apt-get install -y openmpi-bin libopenmpi-dev
 #- export MPI_BASE_DIR=/usr

 - cd $HOME
 - git clone https://github.com/Homebrew/linuxbrew.git
 - export LINUXBREW=$HOME/linuxbrew
 - export PATH=$LINUXBREW/bin:$PATH
 - export LD_LIBRARY_PATH=$LINUXBREW/lib:$LD_LIBRARY_PATH

 # Symlink gcc, gfortran
 - gccver=$(gcc -dumpversion |cut -d. -f1,2)
 - ln -s $(which gcc) $LINUXBREW/bin/gcc-${gccver}
 - ln -s $(which g++) $LINUXBREW/bin/g++-${gccver}
 - ln -s $(which gfortran-${gccver}) $LINUXBREW/bin/gfortran-${gccver}
 - ln -s $(which gfortran-${gccver}) $LINUXBREW/bin/gfortran
 - ln -s $(which mpicc) $LINUXBREW/bin/mpicc
 - ln -s $(which mpic++) $LINUXBREW/bin/mpic++
 - ln -s $(which mpicxx) $LINUXBREW/bin/mpicxx
 - ln -s $(which mpif77) $LINUXBREW/bin/mpif77
 - ln -s $(which mpif90) $LINUXBREW/bin/mpif90

 # Trick Homebrew into believing that the gcc formula is installed.
 - mkdir -p $LINUXBREW/Cellar/gcc/4.9.2_1
 - echo "decoy" > $LINUXBREW/Cellar/gcc/4.9.2_1/somefile.txt
 - mkdir -p $LINUXBREW/Cellar/open-mpi/1.8.4
 - echo "decoy" > $LINUXBREW/Cellar/open-mpi/1.8.4/somefile.txt
 - unset HOMEBREW_VERBOSE

 # Taps used by formulas in Science
 - brew tap homebrew/python
 - brew tap homebrew/versions
 - brew tap homebrew/dupes
 - brew tap homebrew/x11

 - ln -s $TRAVIS_BUILD_DIR $LINUXBREW/Library/Taps/homebrew/homebrew-science
 - brew tap --repair

 # Incorrect file permissions: chmod 644
 - chmod 644 $TRAVIS_BUILD_DIR/*.rb

 # Install pkg-config [see: https://github.com/Homebrew/homebrew-science/pull/1664#issuecomment-69259072]
 - brew install pkg-config
 - brew install -v cmake --without-docs
 - cd $TRAVIS_BUILD_DIR

script:
 #- bash $TRAVIS_BUILD_DIR/travisCI/travis.sh
 - bash $TRAVIS_BUILD_DIR/travisCI/travis_debug.sh

notifications:
 email: false
