language: objective-c  # We're on OSX, with Homebrew.

install:
  - unset DYLD_LIBRARY_PATH
  - brew update
  # Install homebrew-science as tap.
  - mkdir -p $(brew --repo)/Library/Taps/homebrew
  - ln -s $TRAVIS_BUILD_DIR $(brew --repo)/Library/Taps/homebrew/homebrew-science
  - brew tap --repair

script:
  - bash $TRAVIS_BUILD_DIR/travisCI/travis.sh

notifications:
    email: false
